envs:
  staging:
    name: staging
    enabled: true
    common_service: true
    service:
      # - test

  demo:
    name: demo
    enabled: true
    common_service: true
    service:  
        - aidevsecops-app-demo
common_services:
  # - test-svc

 
