jenkins:
  controller:

    installPlugins:
      - configuration-as-code:1998.v3e50e6e9d9d3
      - git:5.8.0
      - git-client:6.4.0
      - docker-plugin:1.10.0
      - jira:3.14
      - slack:761.v2a_8770f0d169
      - maven-plugin:3.26
      - amazon-ecs:1.49
      - junit:1335.v6b_a_a_e18534e1
      - artifactory:4.0.8
      - sonar:2.18
      - workflow-aggregator:600.vb_57cdd26fdd7
      - role-strategy:756.v978cb_392eb_d3
      - kubernetes
      - github-oauth:647.v44f5236c308d
      - matrix-auth:3.2.5
      - job-dsl:1.91

      # BlueOcean (top-level entry only)
      - blueocean:1.27.21

   
# JCasC Configuration under controller
    JCasC:
      enabled: true
      defaultConfig: true
      configScripts:
        welcome-message: |-
          jenkins:
            systemMessage: "Welcome to DEMO CI server. This Jenkins is managed by DEMO team \n\n"


    image:
      registry: "docker.io"  # Registry for the private Docker registry
      repository: "jenkins/jenkins"  # Repository path
      tag: "jdk21"  # Specify the image tag
      pullPolicy: "IfNotPresent"   # Optionally specify the image pull policy

   # Resource settings for the Jenkins controller pod
    replicaCount: 1

    # ----------------------------
    # OPTIMIZED CONTROLLER RESOURCES
    # ----------------------------
    resources:
      requests:
        memory: "3Gi"
        cpu: "500m"
      limits:
        memory: "6Gi"
        cpu: "1500m"
    # ----------------------------
    # OPTIMIZED INIT CONTAINER RESOURCES
    # ----------------------------
    initContainerResources:
      requests:
        memory: "1Gi"
        cpu: "300m"
      limits:
        memory: "3Gi"
        cpu: "500m"
  # Persistent volume settings for Jenkins data
  persistence:
    enabled: true
    storageClass: "standard"
    size: "50Gi"

  sidecars:
    configAutoReload:
      enabled: true

  rbac:
    create: true
    readSecrets: false
    useOpenShiftNonRootSCC: false
